version: "3.1"
services:
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: wordpress2
            MYSQL_PASSWORD: rocket
            MYSQL_ROOT_PASSWORD: rocket 
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - ./conf:/etc/mysql/conf.d
            - persistent:/var/lib/mysql
        networks:
            - default
    web_server:
        image: my-php-app
        container_name: web_server
        restart: always
        ports: 
<<<<<<< Updated upstream
        - 8000:80
        volumes:
        - C:\Users\David\OneDrive\Documentos\GitHub\fp064_p2_TR\project-php:/var/www/html
=======
            - 80:80
        volumes:
            - D:\GitHub\fp064_p2_TR\project-php:/var/www/html
>>>>>>> Stashed changes
        networks:
            - default
        depends_on: 
            - db
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 8001:80
        networks: 
            - default
        environment:
            PMA_HOST: d
            PMA_USER: root
            PMA_PASSWORD: rocket
            PMA_ROOT_PASSWORD: rocket 
volumes:
    persistent: